### ISSUE TITLE
Suggestion for a library + cli nuget package split

### ISSUE THREAD

**Issue by ctolkien** [stevedesmond-ca/dotnet-libyear#1]
Hey Steve,

Handy little tool. I'd like to consume this in a library format from a .netcoreapp - any consideration to splitting this into two nuget packages? One for the core library and then the CLI wrapper over the top?

Edit: To clarify further and as an example, the csproj's I'll be targetting won't exist on disk - so would be handy for there to be some mechanism for handing a string of csproj content.

**Comment by stevedesmond-ca** [comment]
Yeah, there are a couple other usages I had thought of for a library.

Could the quick fix for your example be as simple as allowing an XML string as an argument type?

**Comment by ctolkien** [comment]
>Could the quick fix for your example be as simple as allowing an XML string as an argument type?

It's an option (I could just write the things to disk and then pass it in as well), I'm primarily trying to avoid shelling out to a new process and then having to parse the resulting text. If I can skip that whole step and work with the resulting C# objects instead, that makes my life easier.

**Comment by stevedesmond-ca** [comment]
https://www.nuget.org/packages/libyear-lib/1.0.1 -- feel free to open another issue or PR if you need to be able to pass XML directly into a CsProjFile
