### ISSUE TITLE
Handle * as latest version

### ISSUE THREAD

**Issue by stevedesmond-ca** [stevedesmond-ca/dotnet-libyear#7]

**Comment by mchughmk** [comment]
Do you have any details on this?  I'd love to tackle it if you have more information.

**Comment by stevedesmond-ca** [comment]
lol, I see this is empty -- I remember a conversation somewhere, lemme try to find it and spec it out tonight, but the gist is something like "a version can be listed like `<PackageReference Include="packagename" Version="*"/>` and we want that to:
a) not crash
b) libyear should be 0, as * should get resolved as the latest version

**Comment by mchughmk** [comment]
Makes sense.  I'll start working on that.
